services:
  redis:
    container_name: redis
    image: 'redis:7.4.2'
    ports:
      - "6379:6379"
    restart: always
    networks:
      - auth-service_app-network
  mailing-service:
    container_name: mailing-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - redis
    networks:
      - auth-service_app-network

networks:
  auth-service_app-network:
    external: true
