spring:
  application:
    name: Mailing-Service
  data:
    redis:
      host: redis
      port: 6379

kafka:
  bootstrap-servers: kafka:9092
  consumer:
    group-id: users-group
    auto-offset-reset: earliest
    enable-auto-commit: false

server:
  port: 8089
