spring:
  application:
    name: Mailing-Service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: users-group
      auto-offset-reset: earliest
server:
  port: 8089
